env                  = "production"
location-name        = "east us"
function-size        = "EP2"
function-tier        = "Premium"
sql-sku              = "P1"
apim-sku             = "Standard_1" //Developer_1
apim-publisher_email = "company@terraform.io"
login                = "kooladmin"
pwd                  = "4-v3ry-53cr37-p455w0rd"
